import type { Metadata } from "next";
import "../style/globals.css";
import Header from "@/component/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`scrbar-none`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
